widgetsdir = 'gradience/frontend/widgets'

gradience_sources = [
    '__init__.py',
    'builtin_preset_row.py',
    'color_button.py',
    'custom_css_group.py',
    'custom_themes_group.py',
    'error_list_row.py',
    'explore_preset_row.py',
    'firefox_theming_group.py',
    'icon_theming_group.py',
    'monet_theming_group.py',
    'option_row.py',
    'palette_shades.py',
    'plugin_row.py',
    'preset_row.py',
    'repo_row.py',
    'reset_preset_group.py',
    'shell_theming_group.py',
    'theme_preview.py',
]
PY_INSTALLDIR.install_sources(gradience_sources, subdir: widgetsdir)
