themingdir = 'gradience/backend/theming'

gradience_sources = [
    '__init__.py',
    'backup.py',
    'custom_themes.py',
    'desktop.py',
    'firefox.py',
    'firefox_installer.py',
    'icons.py',
    'monet.py',
    'preset.py',
    'shell.py'
]
PY_INSTALLDIR.install_sources(gradience_sources, subdir: themingdir)
